// // src/app/layout.jsx
// import Curve from './components/Layout/page';
// import './globals.css';
// // import './global.scss';
// // Ensure this path is correct
// import Head from 'next/head';
// // import Curve from '@/components/Layout/Curve';
// import Header from './Header';
// import { AnimatePresence } from 'framer-motion';
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <Head>
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <body>
//         <AnimatePresence>
//           <Header />
//           <Curve backgroundColor={'#B0AD98'}>{children}</Curve>{' '}
//         </AnimatePresence>
//       </body>
//     </html>
//   );
// }
'use client';

import { AnimatePresence } from 'framer-motion';
import Link from 'next/link';
import './globals.css';
// import '@/styles/styles.scss';

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <div className="main">
                    {/* Add the header with navigation links */}
                    <div className="header">
                        <Link href="/">Home</Link>
                        <Link href="/about">About</Link>
                        <Link href="/contact">Contact</Link>
                    </div>

                    {/* Wrap the children in AnimatePresence to handle page transitions */}
                    <AnimatePresence mode="wait">
                        {children}
                    </AnimatePresence>
                </div>
            </body>
        </html>
    );
}
