import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ScrollSection from "@/app/scrollSection"
import CardSlideshow from "@/app/slideshow"
const geistSans = localFont({
  src: "./fonts/Gangitem.otf",
  variable: "--font-gangitem-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  antialiased`}
      >
        <>
        {children}
        <ScrollSection />
       
        {/* <CardSlideshow /> */}
        </>
       
      </body>
    </html>
  );
}
